#!/bin/bash
python3 emit_log.py First message...
python3 emit_log.py Second message......
python3 emit_log.py Third message.
python3 emit_log.py Fourth message......
python3 emit_log.py Fifth message.....